server:
  port: 80
  database: "./data/database.db"
  baseURL:  "/"
  logging:
    - levels: "info|warning|error"
  sources:
    - path: "/files"
      name: "Storage"
      
#frontend:
#  externalLinks:
#    - text: "Radicale"
#      title: "Access your Calendars and Contacts (Radicale)"
#      url: "http://radicale.example.org"
